In [3]:
#rank of array : no. of dimensions
#shape of array: tuple of int giving size of array along each dim

In [4]:
import numpy as np

In [5]:
lst = [1,2,3,4,5,6]
array = np.array(lst, dtype=int)
print(array)

[1 2 3 4 5 6]


In [7]:
print(type(array))
print(len(array)) #no. of elements
print(array.ndim) #no. of dimensions
print(array.shape) #shape of array

<class 'numpy.ndarray'>
6
1
(6,)


In [8]:
array2 = array.reshape(3,2)
print(array2)
array2.shape

[[1 2]
 [3 4]
 [5 6]]


(3, 2)

In [9]:
array3 = array.reshape(3,-1) # -1 is default value for NumPy to figure out that dimension, given one dimension
print(array3) #The other dimension is calculated according to row size = 3
print(array3.ndim)

[[1 2]
 [3 4]
 [5 6]]
2


In [11]:
#init NumPy array from nested Python lists
l1 = [1,2,3,4,5]
l2 = [2,3,4,5,6]
l3 = [3,4,5,6,7]
mul_arr = np.array([l1,l2,l3]) #nested list
print(mul_arr)
print(mul_arr.shape)

[[1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]]
(3, 5)


In [12]:
mul_arr.reshape(1,15)

array([[1, 2, 3, 4, 5, 2, 3, 4, 5, 6, 3, 4, 5, 6, 7]])

In [14]:
a = np.array([[1,2,3],[4,5,6]])
print(a.shape)

(2, 3)


In [15]:
#reshaping, another way. Changes the original array
a.shape = (3,2)
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [18]:
r = range(24)
print(r)
#array of evenly spaced numbers
a = np.arange(24) #start, stop and increment args
print(a)
print(a.shape)
b = a.reshape(6,4,1)
print(b) #makes 6 vectors, of each 4 columns and 1 row

range(0, 24)
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
(24,)
[[[ 0]
  [ 1]
  [ 2]
  [ 3]]

 [[ 4]
  [ 5]
  [ 6]
  [ 7]]

 [[ 8]
  [ 9]
  [10]
  [11]]

 [[12]
  [13]
  [14]
  [15]]

 [[16]
  [17]
  [18]
  [19]]

 [[20]
  [21]
  [22]
  [23]]]


In [22]:
x = np.array([[1,2],[3,4]], dtype = np.float64)
y = np.array([[1,2],[3,4]], dtype = np.float64)
print(x+y)
print(np.add(x,y))
print(x-y)
print(np.subtract(x,y))
print(x*y)
print(np.multiply(x,y))
print(x/y)
print(np.divide(x,y))

[[2. 4.]
 [6. 8.]]
[[2. 4.]
 [6. 8.]]
[[0. 0.]
 [0. 0.]]
[[0. 0.]
 [0. 0.]]
[[ 1.  4.]
 [ 9. 16.]]
[[ 1.  4.]
 [ 9. 16.]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]


In [23]:
#dot product
print(x.dot(y))
print(np.dot(x,y))

[[ 7. 10.]
 [15. 22.]]
[[ 7. 10.]
 [15. 22.]]


In [ ]:
# FUNCTIONS THAT CAN BE PERFORMED
# add
# subtract
# multiply
# divide
# logaddexp  (log of sum of exponent of inputs)
# logaddexp2 (log base 2 of above)
# true_divide (true division)
# floor_divide (returns floor division)
# negative 
# positive
# power
# remainder
# mod (similar to remainder)

In [25]:
#sum of all array elements over given axis
print(x)
print(np.sum(x))

[[1. 2.]
 [3. 4.]]
10.0


In [26]:
print(np.sum(x, axis = 0)) #sum of each column

[4. 6.]


In [27]:
print(np.sum(x, axis = 1)) #sum of each row

[3. 7.]


In [28]:
Fruits = ['grapefruit', 'pineapple', 'blueberries', 'mango', 'banana']
Y=Fruits[::-2]
print(Y)

['banana', 'blueberries', 'grapefruit']


In [29]:
x = [1,2,3,99,99,3,2,1]
x1, x2, x3 = np.split(x, [3,5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


In [32]:
x = ['P','y','t','h','o','n']
for i in enumerate(x):
    print(i, end = " ")

(0, 'P') (1, 'y') (2, 't') (3, 'h') (4, 'o') (5, 'n') 

In [36]:
a = [1,2,3]
b = ['Mat', 'Bat', 'Carpet']
c = zip(a,b)
list(c)

[(1, 'Mat'), (2, 'Bat'), (3, 'Carpet')]

In [38]:
tup = (7,8,9,10,11,12)
print(sum(tup,9))

66


In [39]:
row=np.array([0,1,2])
col=np.array([4,7,8])
np.hstack((row,col))

array([0, 1, 2, 4, 7, 8])

In [40]:
x = [7, 8, 9]; 
x.append(44)
print(x)

[7, 8, 9, 44]


In [46]:
print(l1,l2,l3)
l4 = l1*l2

[1, 2, 3, 4, 5] [2, 3, 4, 5, 6] [3, 4, 5, 6, 7]


TypeError: can't multiply sequence by non-int of type 'list'

In [47]:
fruit={"apple":"red","guava":"green","grape":"purple"}
len(fruit)

3

In [66]:
from array import *

X = [[0,1,2,3],[4,5,6,7],[8,9,10,11]]
X[2]

[8, 9, 10, 11]

In [1]:
x=5
y=3
print(x/y)


1.6666666666666667
